services:
  haga-rpi-temp-logger:
    build:
      context: .
    image: ghcr.io/torstein80/haga-rpi-temp-logger:latest
    container_name: haga-rpi-temp-logger
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      DEFAULT_POLL_SECONDS: "10"
      DEFAULT_INTERVAL_SECONDS: "10"
      DEFAULT_TIMEZONE_OFFSET: "+02:00"
      DB_PATH: "/data/logger.db"
      EXPORT_DIR: "/data/exports"
      W1_BASE_PATH: "/sys/bus/w1/devices"
      SENSOR_LABELS: ""
      HTTPS_CERTFILE: ""
      HTTPS_KEYFILE: ""
      NETWORK_MANAGER_ENABLED: "true"
      NETWORK_AP_INTERFACE: "wlan0"
      NETWORK_AP_CONNECTION_NAME: "haga-fallback-ap"
      NETWORK_WIRED_INTERFACE: "eth0"
      NETWORK_WIRED_CONNECTION_NAME: "haga-eth0"
    volumes:
      - ./data:/data
      - ./certs:/certs:ro
      - /sys/bus/w1/devices:/sys/bus/w1/devices:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /etc/machine-id:/etc/machine-id:ro
